name: CI Pipeline
on: [push, pull_request]
jobs:
  build:
    runs-on: self-hosted 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.24
          
      - name: Build
        run: go build -o my-app .

      - name: Run tests
        run: go test ./...
